shortestPath.exe: shortestPath.o heap.o hash.o
	g++ -o shortestPath.exe shortestPath.o heap.o hash.o 

shortestPath.o: shortestPath.cpp
	g++ -c shortestPath.cpp

heap.o: heap.cpp heap.h
	g++ -c heap.cpp

hash.o: hash.cpp hash.h
	g++ -c hash.cpp


